OTHER_CANCER_TERMS = [
    'embryonal',
    'nodular',
    'transitional',
    'myofibroblastic',
    'oss',
    'fusiform',
    'myoepithelioma',
    'familial',
    'metaplastic',
    'invas',
    'serrated',
    'epithelioma',
    'invasive',
    'carc',
    'myosarcoma',
    'carcinofibroma',
    'enterochromaffin',
    'cystadenocarcinoma',
    'cartilag',
    'well',
    'well-differentiated',
    'balloon',
    'epithelial',
    'neoplasm',
    'polyposis',
    'rectum',
    'nos',
    'basal',
    'differen',
    'verrucous',
    'simplex',
    'composite',
    'coli',
    'mucoepidermoid',
    'neuroendocrine',
    'like',
    'trans',
    'glassy',
    'adenocarc',
    'fibroblastic',
    'fascial',
    'metaplas',
    'angiomyosarcoma',
    'desmoplastic',
    'pleomorphic',
    'sq',
    'ker',
    'tubular',
    'amelanotic',
    'mucosal',
    'signet',
    'tumor',
    'goblet',
    'myoepithelial',
    'liposarcoma',
    'adenoid',
    'basaloid',
    'apocrine',
    'diffuse',
    'carcinoma',
    'mixed',
    'ring',
    'regressing',
    'mal',
    'dedifferentiated',
    'squamous',
    'mucin',
    'atypical',
    'adenosquamous',
    'osteoclast',
    'large',
    'rhabdoid',
    'fibrosarcoma',
    'lg',
    'adenoma',
    'polyps',
    'mult',
    'leiomyosarcoma',
    'spindle',
    'question',
    'cloacogenic',
    'formation',
    'fibromyxosarcoma',
    'epithelioid',
    'pigmented',
    'micro',
    'melanoma',
    'subtypes',
    'sarcoma',
    'undifferentiated',
    'solid',
    'type',
    'mataplasia',
    'duct',
    'sm',
    'stromal',
    'differentiated',
    'and',
    'with',
    'spreading',
    'adenocarcinoid',
    'scirrhous',
    'acinar',
    'papillary',
    'phenotype',
    'clear',
    'adenomatous',
    'producing',
    'cell',
    'metaplasia',
    'adenocarcinoma',
    'hepatoid',
    'epithel',
    'medullary',
    'keratinizing',
    'fibrous',
    'polygonal',
    'micropapillary',
    'small',
    'non',
    'anaplastic',
    'polyp',
    'lentiginous',
    'villous',
    'malignant',
    'tubulovillous',
    'infantile',
    'superficial',
    'solitary',
    'round',
    'horn',
    'cells',
    'w',
    'mucinous',
    'myxoid',
    'carcinosarcoma',
    'nevus',
    'pseudosarcomatous',
    'giant',
    'gastrointestinal',
    'carcinoid',
    'schneiderian',
]

CANCER_SEER_MAYBE = [
    'suspicious', 'apparent', 'apparently', 'appears',
    'consistent', 'compatible', 'comparable', 'favor',
    'favors', 'appearing', 'likely', 'presumed', 'presumptive',
    'presumably', 'presumedly', 'favored',  'suspecting',
    'probable', 'suspect', 'suspected', 'typical', 'typically',
]

CANCER_NEGATION_TERMS = [
    'no', 'not', 'unlikely', 'improbable', 'improbably',
    'doubt', 'doubtful', 'doubted', 'unclear', 'preclude',
    'precludes', 'cannot', 'or',
]

CANCER_MAYBE_TERMS = [  # identified with word embeddings of SEER terms
    'possible', 'possibly', 'suggestive', 'versus',
    'questionable', 'vs', 'v', 'surmise',
    'suggesting', 'possibility',
]
